name: 'Main Workflow'
on: push
jobs:
  check:
    name: 'Check Java Code'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Search for TODOs to convert to Issue
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.EXPODDEV_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}